// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.Rating;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Rating_Roo_Jpa_Entity {
    
    declare @type: Rating: @Entity;
    
    declare @type: Rating: @Table(name = "ratings");
    
}
