// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.Reviewing;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Reviewing_Roo_Jpa_Entity {
    
    declare @type: Reviewing: @Entity;
    
    declare @type: Reviewing: @Table(name = "reviewings");
    
}
