// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.Tag;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tag_Roo_Configurable {
    
    declare @type: Tag: @Configurable;
    
}
