// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.PreferenceDataOnDemand;
import com.agroknow.socnav.domain.PreferenceIntegrationTest;
import com.agroknow.socnav.service.PreferenceService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PreferenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PreferenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PreferenceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PreferenceIntegrationTest: @Transactional;
    
    @Autowired
    PreferenceDataOnDemand PreferenceIntegrationTest.dod;
    
    @Autowired
    PreferenceService PreferenceIntegrationTest.preferenceService;
    
    @Test
    public void PreferenceIntegrationTest.testCountAllPreferences() {
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", dod.getRandomPreference());
        long count = preferenceService.countAllPreferences();
        Assert.assertTrue("Counter for 'Preference' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PreferenceIntegrationTest.testFindPreference() {
        Preference obj = dod.getRandomPreference();
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preference' failed to provide an identifier", id);
        obj = preferenceService.findPreference(id);
        Assert.assertNotNull("Find method for 'Preference' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Preference' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PreferenceIntegrationTest.testFindAllPreferences() {
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", dod.getRandomPreference());
        long count = preferenceService.countAllPreferences();
        Assert.assertTrue("Too expensive to perform a find all test for 'Preference', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Preference> result = preferenceService.findAllPreferences();
        Assert.assertNotNull("Find all method for 'Preference' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Preference' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PreferenceIntegrationTest.testFindPreferenceEntries() {
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", dod.getRandomPreference());
        long count = preferenceService.countAllPreferences();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Preference> result = preferenceService.findPreferenceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Preference' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Preference' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PreferenceIntegrationTest.testFlush() {
        Preference obj = dod.getRandomPreference();
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preference' failed to provide an identifier", id);
        obj = preferenceService.findPreference(id);
        Assert.assertNotNull("Find method for 'Preference' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPreference(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Preference' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PreferenceIntegrationTest.testUpdatePreferenceUpdate() {
        Preference obj = dod.getRandomPreference();
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preference' failed to provide an identifier", id);
        obj = preferenceService.findPreference(id);
        boolean modified =  dod.modifyPreference(obj);
        Integer currentVersion = obj.getVersion();
        Preference merged = preferenceService.updatePreference(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Preference' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PreferenceIntegrationTest.testSavePreference() {
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", dod.getRandomPreference());
        Preference obj = dod.getNewTransientPreference(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Preference' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Preference' identifier to be null", obj.getId());
        preferenceService.savePreference(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Preference' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PreferenceIntegrationTest.testDeletePreference() {
        Preference obj = dod.getRandomPreference();
        Assert.assertNotNull("Data on demand for 'Preference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Preference' failed to provide an identifier", id);
        obj = preferenceService.findPreference(id);
        preferenceService.deletePreference(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Preference' with identifier '" + id + "'", preferenceService.findPreference(id));
    }
    
}
