// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.Item;
import com.agroknow.socnav.domain.ItemDataOnDemand;
import com.agroknow.socnav.domain.Rating;
import com.agroknow.socnav.domain.RatingDataOnDemand;
import com.agroknow.socnav.domain.User;
import com.agroknow.socnav.domain.UserDataOnDemand;
import com.agroknow.socnav.reference.SharingLevelType;
import com.agroknow.socnav.service.RatingService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RatingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RatingDataOnDemand: @Component;
    
    private Random RatingDataOnDemand.rnd = new SecureRandom();
    
    private List<Rating> RatingDataOnDemand.data;
    
    @Autowired
    ItemDataOnDemand RatingDataOnDemand.itemDataOnDemand;
    
    @Autowired
    UserDataOnDemand RatingDataOnDemand.userDataOnDemand;
    
    @Autowired
    RatingService RatingDataOnDemand.ratingService;
    
    public Rating RatingDataOnDemand.getNewTransientRating(int index) {
        Rating obj = new Rating();
        setDomain(obj, index);
        setIp_address(obj, index);
        setItem(obj, index);
        setPreference_avg(obj, index);
        setPreference_dimensions(obj, index);
        setSession_id(obj, index);
        setSharing_level(obj, index);
        setUpdated_at(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void RatingDataOnDemand.setDomain(Rating obj, int index) {
        String domain = "domain_" + index;
        obj.setDomain(domain);
    }
    
    public void RatingDataOnDemand.setIp_address(Rating obj, int index) {
        String ip_address = "ip_address_" + index;
        obj.setIp_address(ip_address);
    }
    
    public void RatingDataOnDemand.setItem(Rating obj, int index) {
        Item item = itemDataOnDemand.getRandomItem();
        obj.setItem(item);
    }
    
    public void RatingDataOnDemand.setPreference_avg(Rating obj, int index) {
        float preference_avg = new Integer(index).floatValue();
        obj.setPreference_avg(preference_avg);
    }
    
    public void RatingDataOnDemand.setPreference_dimensions(Rating obj, int index) {
        int preference_dimensions = index;
        obj.setPreference_dimensions(preference_dimensions);
    }
    
    public void RatingDataOnDemand.setSession_id(Rating obj, int index) {
        String session_id = "session_id_" + index;
        obj.setSession_id(session_id);
    }
    
    public void RatingDataOnDemand.setSharing_level(Rating obj, int index) {
        SharingLevelType sharing_level = SharingLevelType.class.getEnumConstants()[0];
        obj.setSharing_level(sharing_level);
    }
    
    public void RatingDataOnDemand.setUpdated_at(Rating obj, int index) {
        Date updated_at = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdated_at(updated_at);
    }
    
    public void RatingDataOnDemand.setUser(Rating obj, int index) {
        User user = userDataOnDemand.getRandomUser();
        obj.setUser(user);
    }
    
    public Rating RatingDataOnDemand.getSpecificRating(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Rating obj = data.get(index);
        Long id = obj.getId();
        return ratingService.findRating(id);
    }
    
    public Rating RatingDataOnDemand.getRandomRating() {
        init();
        Rating obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ratingService.findRating(id);
    }
    
    public boolean RatingDataOnDemand.modifyRating(Rating obj) {
        return false;
    }
    
    public void RatingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ratingService.findRatingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Rating' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Rating>();
        for (int i = 0; i < 10; i++) {
            Rating obj = getNewTransientRating(i);
            try {
                ratingService.saveRating(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
