// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.RatingDataOnDemand;
import com.agroknow.socnav.domain.RatingIntegrationTest;
import com.agroknow.socnav.service.RatingService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RatingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RatingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RatingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RatingIntegrationTest: @Transactional;
    
    @Autowired
    RatingDataOnDemand RatingIntegrationTest.dod;
    
    @Autowired
    RatingService RatingIntegrationTest.ratingService;
    
    @Test
    public void RatingIntegrationTest.testCountAllRatings() {
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", dod.getRandomRating());
        long count = ratingService.countAllRatings();
        Assert.assertTrue("Counter for 'Rating' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RatingIntegrationTest.testFindRating() {
        Rating obj = dod.getRandomRating();
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rating' failed to provide an identifier", id);
        obj = ratingService.findRating(id);
        Assert.assertNotNull("Find method for 'Rating' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Rating' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RatingIntegrationTest.testFindAllRatings() {
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", dod.getRandomRating());
        long count = ratingService.countAllRatings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Rating', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Rating> result = ratingService.findAllRatings();
        Assert.assertNotNull("Find all method for 'Rating' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Rating' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RatingIntegrationTest.testFindRatingEntries() {
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", dod.getRandomRating());
        long count = ratingService.countAllRatings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Rating> result = ratingService.findRatingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Rating' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Rating' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RatingIntegrationTest.testFlush() {
        Rating obj = dod.getRandomRating();
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rating' failed to provide an identifier", id);
        obj = ratingService.findRating(id);
        Assert.assertNotNull("Find method for 'Rating' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRating(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Rating' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RatingIntegrationTest.testUpdateRatingUpdate() {
        Rating obj = dod.getRandomRating();
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rating' failed to provide an identifier", id);
        obj = ratingService.findRating(id);
        boolean modified =  dod.modifyRating(obj);
        Integer currentVersion = obj.getVersion();
        Rating merged = (Rating)ratingService.updateRating(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Rating' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RatingIntegrationTest.testSaveRating() {
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", dod.getRandomRating());
        Rating obj = dod.getNewTransientRating(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Rating' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Rating' identifier to be null", obj.getId());
        ratingService.saveRating(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Rating' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RatingIntegrationTest.testDeleteRating() {
        Rating obj = dod.getRandomRating();
        Assert.assertNotNull("Data on demand for 'Rating' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Rating' failed to provide an identifier", id);
        obj = ratingService.findRating(id);
        ratingService.deleteRating(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Rating' with identifier '" + id + "'", ratingService.findRating(id));
    }
    
}
