// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.ReviewingDataOnDemand;
import com.agroknow.socnav.domain.ReviewingIntegrationTest;
import com.agroknow.socnav.service.ReviewingService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReviewingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReviewingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReviewingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReviewingIntegrationTest: @Transactional;
    
    @Autowired
    ReviewingDataOnDemand ReviewingIntegrationTest.dod;
    
    @Autowired
    ReviewingService ReviewingIntegrationTest.reviewingService;
    
    @Test
    public void ReviewingIntegrationTest.testCountAllReviewings() {
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", dod.getRandomReviewing());
        long count = reviewingService.countAllReviewings();
        Assert.assertTrue("Counter for 'Reviewing' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReviewingIntegrationTest.testFindReviewing() {
        Reviewing obj = dod.getRandomReviewing();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to provide an identifier", id);
        obj = reviewingService.findReviewing(id);
        Assert.assertNotNull("Find method for 'Reviewing' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Reviewing' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReviewingIntegrationTest.testFindAllReviewings() {
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", dod.getRandomReviewing());
        long count = reviewingService.countAllReviewings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Reviewing', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Reviewing> result = reviewingService.findAllReviewings();
        Assert.assertNotNull("Find all method for 'Reviewing' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Reviewing' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReviewingIntegrationTest.testFindReviewingEntries() {
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", dod.getRandomReviewing());
        long count = reviewingService.countAllReviewings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Reviewing> result = reviewingService.findReviewingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Reviewing' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Reviewing' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReviewingIntegrationTest.testFlush() {
        Reviewing obj = dod.getRandomReviewing();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to provide an identifier", id);
        obj = reviewingService.findReviewing(id);
        Assert.assertNotNull("Find method for 'Reviewing' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReviewing(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Reviewing' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewingIntegrationTest.testUpdateReviewingUpdate() {
        Reviewing obj = dod.getRandomReviewing();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to provide an identifier", id);
        obj = reviewingService.findReviewing(id);
        boolean modified =  dod.modifyReviewing(obj);
        Integer currentVersion = obj.getVersion();
        Reviewing merged = (Reviewing)reviewingService.updateReviewing(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Reviewing' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewingIntegrationTest.testSaveReviewing() {
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", dod.getRandomReviewing());
        Reviewing obj = dod.getNewTransientReviewing(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Reviewing' identifier to be null", obj.getId());
        reviewingService.saveReviewing(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Reviewing' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReviewingIntegrationTest.testDeleteReviewing() {
        Reviewing obj = dod.getRandomReviewing();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Reviewing' failed to provide an identifier", id);
        obj = reviewingService.findReviewing(id);
        reviewingService.deleteReviewing(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Reviewing' with identifier '" + id + "'", reviewingService.findReviewing(id));
    }
    
}
