// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.TaggingDataOnDemand;
import com.agroknow.socnav.domain.TaggingIntegrationTest;
import com.agroknow.socnav.service.TaggingService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TaggingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TaggingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TaggingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TaggingIntegrationTest: @Transactional;
    
    @Autowired
    TaggingDataOnDemand TaggingIntegrationTest.dod;
    
    @Autowired
    TaggingService TaggingIntegrationTest.taggingService;
    
    @Test
    public void TaggingIntegrationTest.testCountAllTaggings() {
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", dod.getRandomTagging());
        long count = taggingService.countAllTaggings();
        Assert.assertTrue("Counter for 'Tagging' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TaggingIntegrationTest.testFindTagging() {
        Tagging obj = dod.getRandomTagging();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to provide an identifier", id);
        obj = taggingService.findTagging(id);
        Assert.assertNotNull("Find method for 'Tagging' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tagging' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TaggingIntegrationTest.testFindAllTaggings() {
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", dod.getRandomTagging());
        long count = taggingService.countAllTaggings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tagging', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tagging> result = taggingService.findAllTaggings();
        Assert.assertNotNull("Find all method for 'Tagging' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tagging' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TaggingIntegrationTest.testFindTaggingEntries() {
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", dod.getRandomTagging());
        long count = taggingService.countAllTaggings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tagging> result = taggingService.findTaggingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tagging' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tagging' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TaggingIntegrationTest.testFlush() {
        Tagging obj = dod.getRandomTagging();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to provide an identifier", id);
        obj = taggingService.findTagging(id);
        Assert.assertNotNull("Find method for 'Tagging' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTagging(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tagging' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaggingIntegrationTest.testUpdateTaggingUpdate() {
        Tagging obj = dod.getRandomTagging();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to provide an identifier", id);
        obj = taggingService.findTagging(id);
        boolean modified =  dod.modifyTagging(obj);
        Integer currentVersion = obj.getVersion();
        Tagging merged = (Tagging)taggingService.updateTagging(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tagging' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TaggingIntegrationTest.testSaveTagging() {
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", dod.getRandomTagging());
        Tagging obj = dod.getNewTransientTagging(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tagging' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tagging' identifier to be null", obj.getId());
        taggingService.saveTagging(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'Tagging' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TaggingIntegrationTest.testDeleteTagging() {
        Tagging obj = dod.getRandomTagging();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tagging' failed to provide an identifier", id);
        obj = taggingService.findTagging(id);
        taggingService.deleteTagging(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Tagging' with identifier '" + id + "'", taggingService.findTagging(id));
    }
    
}
