// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agroknow.socnav.domain;

import com.agroknow.socnav.domain.Item;
import com.agroknow.socnav.domain.ItemDataOnDemand;
import com.agroknow.socnav.domain.Tagging;
import com.agroknow.socnav.domain.TaggingDataOnDemand;
import com.agroknow.socnav.domain.User;
import com.agroknow.socnav.domain.UserDataOnDemand;
import com.agroknow.socnav.reference.SharingLevelType;
import com.agroknow.socnav.service.TaggingService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TaggingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TaggingDataOnDemand: @Component;
    
    private Random TaggingDataOnDemand.rnd = new SecureRandom();
    
    private List<Tagging> TaggingDataOnDemand.data;
    
    @Autowired
    ItemDataOnDemand TaggingDataOnDemand.itemDataOnDemand;
    
    @Autowired
    UserDataOnDemand TaggingDataOnDemand.userDataOnDemand;
    
    @Autowired
    TaggingService TaggingDataOnDemand.taggingService;
    
    public Tagging TaggingDataOnDemand.getNewTransientTagging(int index) {
        Tagging obj = new Tagging();
        setDomain(obj, index);
        setIp_address(obj, index);
        setItem(obj, index);
        setSession_id(obj, index);
        setSharing_level(obj, index);
        setUpdated_at(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void TaggingDataOnDemand.setDomain(Tagging obj, int index) {
        String domain = "domain_" + index;
        obj.setDomain(domain);
    }
    
    public void TaggingDataOnDemand.setIp_address(Tagging obj, int index) {
        String ip_address = "ip_address_" + index;
        obj.setIp_address(ip_address);
    }
    
    public void TaggingDataOnDemand.setItem(Tagging obj, int index) {
        Item item = itemDataOnDemand.getRandomItem();
        obj.setItem(item);
    }
    
    public void TaggingDataOnDemand.setSession_id(Tagging obj, int index) {
        String session_id = "session_id_" + index;
        obj.setSession_id(session_id);
    }
    
    public void TaggingDataOnDemand.setSharing_level(Tagging obj, int index) {
        SharingLevelType sharing_level = SharingLevelType.class.getEnumConstants()[0];
        obj.setSharing_level(sharing_level);
    }
    
    public void TaggingDataOnDemand.setUpdated_at(Tagging obj, int index) {
        Date updated_at = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdated_at(updated_at);
    }
    
    public void TaggingDataOnDemand.setUser(Tagging obj, int index) {
        User user = userDataOnDemand.getRandomUser();
        obj.setUser(user);
    }
    
    public Tagging TaggingDataOnDemand.getSpecificTagging(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Tagging obj = data.get(index);
        Long id = obj.getId();
        return taggingService.findTagging(id);
    }
    
    public Tagging TaggingDataOnDemand.getRandomTagging() {
        init();
        Tagging obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return taggingService.findTagging(id);
    }
    
    public boolean TaggingDataOnDemand.modifyTagging(Tagging obj) {
        return false;
    }
    
    public void TaggingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = taggingService.findTaggingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Tagging' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Tagging>();
        for (int i = 0; i < 10; i++) {
            Tagging obj = getNewTransientTagging(i);
            try {
                taggingService.saveTagging(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
